### ISSUE TITLE
Loading required namespace: rmarkdown lidR::tree_detection is deprecated. Use find_trees instead.

### ISSUE THREAD

**Issue by atkinsjeff** [carlos-alberto-silva/weblidar-treetop#8]
I noticed this error this morning when running the code:

Loading required namespace: rmarkdown
lidR::tree_detection is deprecated. Use find_trees instead.

Nothing major, but wanted to document

**Comment by caiohamamura** [comment]
Fixed by 70582cf77dbbc4269b01d9b753c043dda593eeb7 and b8612e47bd87789a8e4c49ebfbb8305eae2519ba
