### ISSUE TITLE
Unable to download shp

### ISSUE THREAD

**Issue by AAmeen112** [carlos-alberto-silva/weblidar-treetop#9]
I have notices that every time I try to download the shp after processing, it says: "Failed - No file". The csv and image files download fine. Could you please assist me with this regards.

Thank you

**Comment by BigEyePuna** [comment]
I have the same problem, not being able to download the shapefiles. I can save the .csv and create points from XY in GIS software but I don't have any way to view the crown polygons.  The error message that pops up for me in R is "Warning: Error in <-: could not find function "proj4string<-"
  [No stack trace available]

Any resolution to this?

**Comment by caiohamamura** [comment]
Solved by 01bc808c20130c1f42ea94b7154237e43bdab434 by importing `sp::proj4string`
